config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'hot' => 'static_pages#hot'
  get 'categorys/:id' => 'categorys#show', as: :category
  get 'great' => 'static_pages#great'

  devise_for :users
  get 'user/:id' => 'users#show', as: :user
  get 'user/:id/followers' => 'users#followers', as: :followers
  get 'user/:id/followeds' => 'users#followings', as: :followings

  resources :abstract_targets, only: [:new, :create, :show]

  resources :targets do
     resources :days
     member do
      patch 'like'
      patch 'unlike'
    end
  end

  post 'comments/create' => 'comments#create'

  delete 'comments/:id' => 'comments#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :admins, only: [:index] do
    collection do
      get :targets
      delete :delete_target
      get :abstract_targets
      delete :delete_abstract_target
      get :users
      delete :delete_user
      get :log_in
      post 'log_in' => 'admins#session_create'
      delete :log_out
      patch :change_category
      patch :mark_great
    end
  end

 

end

app/models/target.rb
class Target < ActiveRecord::Base
  include Timeago
  
  belongs_to :user
  belongs_to :abstract_target
  has_many :days, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_and_belongs_to_many :like_users, class_name: "User", foreign_key: 'target_id', association_foreign_key: "user_id", join_table: 'likeable_targets_like_users'

  validates :start_time, :finish_time, presence: true
  validate :time_cannot_be_in_the_past, :finish_time_cannot_earlier_than_start_time

  self.per_page = 8

  scope :great, -> { where('great = ?', 1) }

  def name
    abstract_target.name
  end

  def detail
    abstract_target.detail
  end

  def category
    abstract_target.category
  end

  def followed_users
    abstract_target.users
  end

  def followed_targets
    abstract_target.targets
  end

  def plan_days_count
    (finish_time - start_time).to_i
  end

  def percent
    ((days.count.to_f / plan_days_count) * 100).to_i
  end

  def followed?(user)
    abstract_target.users.include?(user)
  end

  def liked?(user)
    like_users.include?(user)
  end

  def record_today?
    days.find_by_date_at(Date.today) ? true : false
  end

  def self.from_followings_by(user)
    following_ids = user.following_ids
    where("user_id IN (?)", following_ids)
  end

  def time_cannot_be_in_the_past
  	if start_time.present? && start_time < Date.today
  		errors.add(:start_time, "开始时间不能早于今日日期")
  	end
  	if finish_time.present? && finish_time < Date.today
  		errors.add(:finish_time, "结束时间不能早于今日日期")
  	end
  end

  def finish_time_cannot_earlier_than_start_time
  	if start_time.present? && finish_time.present? && finish_time < start_time
  		errors.add(:finish_time, "结束时间不能早于开始时间")
  	end
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @targets = current_user.targets.order(created_at: :desc).paginate(:page => params[:page])
  end

  def show
    @target = Target.find(params[:id])
    @comments = @target.comments.root.order(created_at: :desc).paginate(:page => params[:page], :per_page => 6)
    @today = @target.days.new
    
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def create
    @target = Target.new(follow_params)
    if @target.abstract_target.users.include?(current_user)
      flash[:error] = "对不起，您已有该目标"
      redirect_to @target.abstract_target.targets.find_by_user_id(current_user.id)
    else
      @target.user = current_user
      @target.save
      redirect_to @target
    end
  end


  def edit
  end

  def update
  end

  def destroy
    @target = Target.find(params[:id])
    if @target.user_id == current_user.id
      @target.destroy
      @target.abstract_target.destroy if @target.abstract_target.targets.empty?
    end
    redirect_to root_path
  end

  def like
    @target = Target.find(params[:id])
    if @target.user != current_user && !@target.liked?(current_user)
      @target.like_users << current_user
    end
    respond_to do |format|
      format.html { redirect_to @target }
      format.js {}
    end
  end

  def unlike
    @target = Target.find(params[:id])
    @target.like_users.destroy(current_user) if @target.liked?(current_user)
    respond_to do |format|
      format.html { redirect_to @target }
      format.js {}
    end
  end

  private
    def follow_params
      params.require(:target).permit(:start_time, :finish_time, :abstract_target_id)
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_card.html.erb
<%= link_to target_path(target), class: "ui card" do %>
	<div class="content">
		<div class="header">
			<%= target.name %>
			<% if target.record_today? %>
				<i class="green check square icon" title="已打卡"></i>
			<% else %>
				<i class="disabled check square icon" title="未打卡"></i>
			<% end %>
		</div>
		<div class="meta"><span class="category"><%= target.category.name %></span>
		</div>
		<div class="description"><%= target.detail %></div>
	</div>
	<div class="ui top right attached teal label">
		<i class="icon pointing up"></i><%= target.hits %>			
	</div>
	<div class="extra content">
		<div class="ui left floated black label">
			打卡
			<div class="detail">
				<%= target.days.count %>
			</div>
		</div>
		<div class="ui left floated purple label">
			参与
			<div class="detail">
				<%= target.followed_users.count %>
			</div>
		</div>
		<div class="ui left floated pink label">
			<i class="heart icon"></i><%= target.like_users.count %>
		</div>
		<div class="ui left floated green label">
			<i class="comment icon"></i><%= target.comments.count %>
		</div>
		<div class="right floated author">
			<%= image_tag target.user.avatar.url, class: "ui avatar image" %><%= target.user.name %>
		</div>
	</div>
	<div class="ui red bottom attached progress" id="card_progress" data-percent=<%= target.percent %>>
		<div class="bar"></div>
	</div>		
<% end %>

app/views/targets/_follow_part.html.erb
<div id="follow_part">
	<div class="ui horizontal statistics">
		<%= link_to abstract_target_path(target.abstract_target), class: "purple statistic" do %>
			<div class="value"><%= target.followed_users.count %></div>
			<div class="label">人也建立了该目标</div>
		<% end %>
		<div class="pink statistic">
			<div class="value"><%= target.like_users.count %></div>
			<div class="label">人赞过</div>
		</div>
	</div>
	<div class="ui buttons">
		<% if target.followed?(current_user) %>
			<%= link_to "我的进度", target_path(target.followed_targets.find_by(user: current_user)), class: "ui blue button" %>
		<% else %>
			<div class="ui blue button" id="follow_button">建立目标</div>
			<%= render partial: 'targets/follow_part_modal', locals: { target: target.abstract_target.targets.new } %>
		<% end %>

		<% if target.liked?(current_user) %>
			<%= form_for(target, url: { action: "unlike" }, remote: true, html: { style: "display: inline;" }) do |f| %>
				<%= f.submit "已赞", class: "ui button" %>
			<% end %>
		<% else %>
			<%= form_for(target, url: { action: "like" }, remote: true, html: { style: "display: inline;"}) do |f| %>
				<%= f.submit "赞", class: "ui pink button" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/targets/_follow_part_modal.html.erb
<div class="ui modal">
  <i class="close icon"></i>
  <div class="header">建立该目标</div>
  <div class="content">
    <div class="image"><i class="trophy icon"></i></div>
    <div class="description">
      <%= form_for target, url: targets_path, html: { class: "ui form" } do |f| %>
        <div class="field">
          <%= f.label :start_time, '开始时间' %>
          <%= f.date_field :start_time %>
        </div>
        <div class="field">
          <%= f.label :finish_time, '结束时间' %>
          <%= f.date_field :finish_time %>
        </div>
        <%= f.hidden_field :abstract_target_id %>
        <div class="field">
          <%= f.submit '提交', class: "ui blue button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/targets/_sidebar.html.erb
<div class="ui card">
	<div class="content">
		<div class="header"><%=image_tag current_user.avatar.url, class: "ui avatar image" %><%= link_to current_user.name, user_path(current_user) %></div>
		<div class="description"><%= current_user.introduce %></div>
	</div>
	<div class="ui bottom attached 2 fluid buttons">
		<%= link_to new_abstract_target_path, class: "ui blue button" do %>
			<i class="add icon"></i>创建新目标
		<% end %>
		<div class="or"></div>
		<%= link_to targets_path, class: "ui pink button" do %>
			<i class="user icon"></i>我的目标
		<% end %>
	</div>
</div>

<%= render partial: 'relationships/follow', locals: { user: current_user } %>

<div class="ui accordion">
	<h4 class="ui top attached header inverted title">
		人生的六个高度理论
	</h4>
	<div class="ui attached content segment">
		<ol>
			<li>原则（个人的价值观 原则 目标）</li>
			<li>愿景（3-5年的工作目标）</li>
			<li>目标（1-2年的阶段性成果）</li>
			<li>责任范围（工作上的角色，生活中的角色）</li>
			<li>任务（需要一步以上完成的事情）</li>
			<li>下一步行动（切实具体的动作）</li>
		</ol>
	</div>
</div>

<h4 class="ui top attached header">使用指南</h4>
<div class="ui attached segment">
	<ul>
		<li>根据六个高度理论审视自己</li>
		<li>根据自己的目标创建新目标</li>
		<li>设置目标的内容和时间</li>
		<li>每天坚持打卡</li>
		<li>最终完成目标</li>
	</ul>
</div>

<h4 class="ui top attached header">统计信息</h4>
<div class="ui attached segment">
	<ul>
		<li>建立目标：<%= current_user.targets.count %></li>
		<li>打卡：<%= current_user.days.count %></li>
		<li>赞过：<%= current_user.likeable_targets.count %></li>
	</ul>
</div>

<h4 class="ui top attached header">全站统计</h4>
<div class="ui attached segment">
	<ul>
		<li>全站目标总数：<%= Target.all.count %></li>
		<li>全站打卡天数：<%= Day.all.count %></li>
		<li>会员总数：<%= User.all.count %></li>
	</ul>
</div>

app/views/targets/create.html.erb
<h1>Targets#create</h1>
<p>Find me in app/views/targets/create.html.erb</p>

app/views/targets/destroy.html.erb
<h1>Targets#destroy</h1>
<p>Find me in app/views/targets/destroy.html.erb</p>

app/views/targets/index.html.erb
<% provide(:title, "我的目标") %>

<div class="ui grid">
	<div class="twelve wide column">
		<div class="ui dividing header">
			我的目标
		</div>
		<div class="ui two cards">
			<% @targets.each do |target| %>
				<%= render partial: 'targets/card', locals: { target: target } %>
			<% end %>
		</div>
		<%= will_paginate @targets, { class: "flickr_pagination", next_label: ">>", previous_label: "<<" } %>
	</div>
	<div class="four wide column">
		<%= render 'sidebar' %>
	</div>
</div>

app/views/targets/like.js.erb
$('#follow_part').replaceWith("<%= j render partial: 'follow_part', locals: { target: @target } %>");

app/views/targets/new.html.erb
<% provide(:title, "新建目标") %>

<div class="ui grid">
	<div class="twelve wide column">
		<div class="ui dividing header">创建新目标</div>
		<% if @abstract_target.errors.any? %>
			<div class="ui warning message">
				<div class="header">请检查您的输入</div>
				<ul class="list">
					<% @abstract_target.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<%= form_for @abstract_target,url: { controller: :targets, action: :create }, html: { class: "ui large form segment", role: "form" } do |f| %>
			<div class="inline field">
				<%= f.label :name, "目标标题：" %>
				<%= f.text_field :name, class: "twelve wide field", placeholder: "例如：锻炼身体" %>
			</div>
			<div class="inline field">
				<%= f.label :detail, "目标描述：" %>
				<%= f.text_area :detail, class: "twelve wide field", placeholder: "例如：深蹲15个 平板支撑45秒 每天10组" %>
			</div>
			<div class="inline field">
				<%= f.label :category_id, "目标分类：" %>
				<%= f.select :category_id, [["学习", 1], ["工作", 2], ["生活", 3], ["健康", 4]], {}, class: "ui dropdown six wide field" %>
			</div>
			<%= f.fields_for :targets do |target_f| %>
				<div class="inline field">
					<%= target_f.label :start_time, "开始时间：" %>
					<%= target_f.date_field :start_time, class: "six wide field" %>
				</div>
				<div class="inline field">
					<%= target_f.label :finish_time, "结束时间：" %>
					<%= target_f.date_field :finish_time, class: "six wide field" %>
				</div>
			<% end %>
			<div class="inline field">
				<%= f.submit "提交", class: "ui blue button" %>
			</div>
		<% end %>
	</div>
	<div class="four wide column"><%= render 'targets/sidebar' %></div>
</div>

app/views/targets/show.html.erb
<% provide(:title, @target.name) %>

<div class="ui grid">
	<div class="twelve wide column">
		<h3 class="ui top attached header"><i class="icon trophy"></i><%= @target.name %></h3>
		<div class="ui attached segment">
			<div class="ui vertical segment">
				<div class="ui grid">
					<div class="twelve wide column">
						<div class="ui horizontal list">
							<div class="ui teal large label"><i class="icon play"></i>开始时间：<%= @target.start_time %></div>
							<div class="ui orange large label"><i class="icon stop"></i>结束时间：<%= @target.finish_time %></div>
						</div>
						<%= link_to "删除目标", target_path(@target), method: :delete, class: "ui tiny red button" if @target.user == current_user %>
						<div class="ui green message">
							<i class="icon content"></i>目标描述：
							<p><%= @target.detail %></p>
						</div>
					</div>
					<div class="four wide column">
						<% if @target.user == current_user %>
							<%= form_for @today, url: target_days_path(@target, @today), html: { class: "ui small form", role: "form" } do |f| %>
								<div class="field">
									<%= f.text_area :comment, size: "2x2" %>
									<%= @target.days.find_by(date_at: Date.today) ? f.submit("已打卡", class: "ui disabled button") : f.submit("打卡", class: "ui blue button") %>
									<div class="ui teal tag label">今日记录</div>
								</div>
							<% end %>
						<% else %>
							<%= render partial: 'follow_part', locals: { target: @target } %>
						<% end %>
					</div>
				</div>
			</div>
			<div class="ui vertical segment">
				<div class="ui grid">
					<div class="twelve wide column">
						<div id="calendar" 
						<% n = 0 %>
						<% @target.days.each do |day| %>
							data-date-<%= n %>="<%= day.date_at %>"
							data-date-url-<%= n %>="<%= target_day_path(@target, day) unless day.new_record? %>"
							<% n += 1 %>
						<% end %>
						></div>
					</div>
					
					<div class="four wide column">
						<div class="ui small statistics">
							<div class="statistic">
								<div class="value"><%= @target.days.count %></div>
								<div class="label">打卡统计</div>
							</div>
							<div class="statistic">
								<div class="value"><%= (@target.finish_time - Date.today).to_i %></div>
								<div class="label">剩余时间</div>
							</div>
							<div class="statistic">
								<div class="value"><%= ((@target.days.count.to_f / (@target.finish_time - @target.start_time)) * 100).to_i %>%</div>
								<div class="label">完成度</div>
							</div>
							<div class="statistic">
								<div class="value"><%= @target.hits %></div>
								<div class="label">点击</div>
							</div>
						</div>
						
					</div>
					
				</div>
			</div>
		</div>

		<div class="ui four cards">
			<% @target.days.last(3).each do |day| %>
				<div class="card">
					<div class="content">
						<div class="header"><%= day.date_at || "暂无记录" %></div>
						<div class="meta"></div>
						<div class="description"><%= day.comment || "显示最近打卡日记录" %></div>
					</div>
				</div>
			<% end %>
			<div class="card" id="today">
				<div class="content">
					<div class="header">未指定</div>
					<div class="description">请在日历上选择要查看的日期</div>
				</div>
			</div>
		</div>

		<%= link_to "展开评论", target_path(@target), class: "fluid ui big blue inverted button", id: "toggle_comment", remote: true %>

		<% unless @target.followed_users.empty? %>
			<div class="ui small header">
				他们也建立了该目标
			</div>

			<div class="ui eight doubling cards">
				<% @target.followed_targets.limit(8).each do |followed_target| %>
					<%= link_to target_path(followed_target), class: "card" do %>
						<div class="image"><%= image_tag followed_target.user.avatar.url %></div>
						<div class="content">
							<div class="header"><%= followed_target.user.name %></div>
							<div class="meta">
								<div>打卡<%= followed_target.days.count %>天</div>
							</div>
						</div>
						<div class="extra content">
							<div>完成度<%= followed_target.percent %>%</div>
						</div>
					<% end %>
				<% end %>
			</div>
		<% end %>
		

	</div>

	<div class="four wide column">
		<% if @target.user == current_user %>
			<%= render 'sidebar' %>
		<% else %>
			<%= render partial: 'users/sidebar', locals: { user: @target.user } %>
		<% end %>
	</div>
</div>

app/views/targets/show.js.erb
$('#toggle_comment').after("<%= j render partial: 'comments/list', locals: { target: @target, comments: @comments } %>");
$('#toggle_comment').remove();
$('#comments').replaceWith("<%= j render partial: 'comments/list', locals: { target: @target, comments: @comments } %>");
$('#comments_paginate').find('a').attr("data-remote", true);
$(".reply_toggle").click(function(){
	$(this).parent().siblings('.reply_form').toggle();
});

app/views/targets/unfollowed.js.erb
$('#follow_part').replaceWith("<%= j render partial: 'follow_part', locals: { target: @target } %>");

app/views/targets/unlike.js.erb
$('#follow_part').replaceWith("<%= j render partial: 'follow_part', locals: { target: @target } %>");

app/views/targets/update.html.erb
<h1>Targets#update</h1>
<p>Find me in app/views/targets/update.html.erb</p>