config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'hot' => 'static_pages#hot'
  get 'categorys/:id' => 'categorys#show', as: :category
  get 'great' => 'static_pages#great'

  devise_for :users
  get 'user/:id' => 'users#show', as: :user
  get 'user/:id/followers' => 'users#followers', as: :followers
  get 'user/:id/followeds' => 'users#followings', as: :followings

  resources :abstract_targets, only: [:new, :create, :show]

  resources :targets do
     resources :days
     member do
      patch 'like'
      patch 'unlike'
    end
  end

  post 'comments/create' => 'comments#create'

  delete 'comments/:id' => 'comments#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :admins, only: [:index] do
    collection do
      get :targets
      delete :delete_target
      get :abstract_targets
      delete :delete_abstract_target
      get :users
      delete :delete_user
      get :log_in
      post 'log_in' => 'admins#session_create'
      delete :log_out
      patch :change_category
      patch :mark_great
    end
  end

 

end

app/views/admins/_header.html.erb
<div class="container">
  <div class="ui menu">
    <%= link_to "前台", root_path, class: "item" %>
    <%= link_to "目标列表", targets_admins_path, class: "item" %>
    <%= link_to "抽象目标列表", abstract_targets_admins_path, class: "item" %>
    <%= link_to "用户列表", users_admins_path, class: "item" %>

    <div class="right menu">
      <%= link_to "登出", log_out_admins_path, method: :delete, class: "item" %>
    </div>
  </div>
</div>

app/views/admins/abstract_targets.html.erb
<h1>抽象目标列表</h1>
<table class="ui table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>User</th>
      <th>hits</th>
      <th>category</th>
      <th>great</th>
      <th>delete</th>
    </tr>
  </thead>
  <tbody>
    <% @abstract_targets.each do |abstract_target| %>
      <tr>
        <td><%= abstract_target.id %></td>
        <td><%= abstract_target.name %></td>
        <td><%= abstract_target.users.count %></td>
        <td><%= abstract_target.hits %></td>
        <td>
          <%= link_to abstract_target.category.name, '#', class: "ctg" %>
          <div class="ui modal">
            <i class="close icon"></i>
            <div class="header">更改类别</div>
            <div class="content">
              <%= form_for abstract_target, url: change_category_admins_path(a_t: abstract_target.id), html: { class: "ui form"} do |f| %>
                <%= f.label :category_id, "类别" %>
                <%= f.select :category_id, Category.all.collect { |c| [c.name, c.id] } %>
                <%= f.submit "提交", class: "ui submit button" %>
              <% end %>
            </div>
          </div>  
        </td>
        <td><%= link_to abstract_target.great.to_s, mark_great_admins_path(a_t: abstract_target.id), method: :patch %></td>
        <td><%= link_to "delete", { controller: "admins", action: "delete_abstract_target", abstract_target_id: "#{abstract_target.id}" }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @abstract_targets %>

app/views/admins/change_category.html.erb
<h1>Admins#change_category</h1>
<p>Find me in app/views/admins/change_category.html.erb</p>

app/views/admins/delete_target.html.erb
<h1>Admins#delete_target</h1>
<p>Find me in app/views/admins/delete_target.html.erb</p>

app/views/admins/delete_user.html.erb
<h1>Admins#delete_user</h1>
<p>Find me in app/views/admins/delete_user.html.erb</p>

app/views/admins/log_in.html.erb
<% provide(:title, "后台登陆") %>

<div class="ui header">后台登陆</div>

<%= form_for :admin, url: { controller: :admins, action: :session_create }, html: { class: "ui form basic segment admin-sign-in" } do |f| %>
  <div class="inline field">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="inline field">
    <%= f.password_field :password, placeholder: "Password" %>
  </div>
  <%= f.submit "登陆", class: "ui submit blue button" %>
<% end %>

app/views/admins/log_out.html.erb
<h1>Admins#log_out</h1>
<p>Find me in app/views/admins/log_out.html.erb</p>

app/views/admins/mark_great.html.erb
<h1>Admins#mark_great</h1>
<p>Find me in app/views/admins/mark_great.html.erb</p>

app/views/admins/session_create.html.erb
<h1>Admins#session_create</h1>
<p>Find me in app/views/admins/session_create.html.erb</p>

app/views/admins/targets.html.erb
<h1>目标列表</h1>
<table class="ui table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>User</th>
      <th>StartTime</th>
      <th>FinishTime</th>
      <th>Days</th>
      <th>hits</th>
      <th>delete</th>
    </tr>
  </thead>
  <tbody>
    <% @targets.each do |target| %>
      <tr>
        <td><%= target.id %></td>
        <td><%= target.name %></td>
        <td><%= target.user.name %></td>
        <td><%= target.start_time %></td>
        <td><%= target.finish_time %></td>
        <td><%= target.days.count %></td>
        <td><%= target.hits %></td>
        <td><%= link_to "delete", { controller: "admins", action: "delete_target", target_id: "#{target.id}" }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @targets %>

app/views/admins/users.html.erb
<h1>用户列表</h1>
<table class="ui table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>TargetsCount</th>
      <th>DaysCount</th>
      <th>Followers</th>
      <th>Followings</th>
      <th>CreatedTime</th>
      <th>删除</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.targets.count %></td>
        <td><%= user.days.count %></td>
        <td><%= user.followers.count %></td>
        <td><%= user.followings.count %></td>
        <td><%= user.created_at %></td>
        <td><%= link_to "delete", { controller: "admins", action: "delete_user", user_id: "#{user.id}" }, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @users %>