config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  get 'hot' => 'static_pages#hot'
  get 'categorys/:id' => 'categorys#show', as: :category
  get 'great' => 'static_pages#great'

  devise_for :users
  get 'user/:id' => 'users#show', as: :user
  get 'user/:id/followers' => 'users#followers', as: :followers
  get 'user/:id/followeds' => 'users#followings', as: :followings

  resources :abstract_targets, only: [:new, :create, :show]

  resources :targets do
     resources :days
     member do
      patch 'like'
      patch 'unlike'
    end
  end

  post 'comments/create' => 'comments#create'

  delete 'comments/:id' => 'comments#destroy'

  resources :relationships, only: [:create, :destroy]

  resources :admins, only: [:index] do
    collection do
      get :targets
      delete :delete_target
      get :abstract_targets
      delete :delete_abstract_target
      get :users
      delete :delete_user
      get :log_in
      post 'log_in' => 'admins#session_create'
      delete :log_out
      patch :change_category
      patch :mark_great
    end
  end

 

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base

	include Timeago
	
	belongs_to :following, class_name: "User"
	belongs_to :follower, class_name: "User"

	def self.from_followings_by(user)
		following_ids = user.following_ids
		where("follower_id IN (?)", following_ids)
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  	@user = User.find(params[:relationship][:following_id])
    unless current_user.followings.include?(@user) || current_user == @user
    	current_user.relationships.create!(following_id: @user.id) 
    end
    respond_to do |format|
      format.html { redirect_to @user }
      format.js {}
    end
  	
  end

  def destroy
  	@user = User.find(params[:relationship][:following_id])
    if current_user.followings.include?(@user)
    	current_user.relationships.find_by(following_id: @user.id).destroy
    end
  	respond_to do |format|
      format.html { redirect_to @user }
      format.js {}
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
<div class="ui inverted segment" id="follow">
	<div class="ui grid">
		<div class="ui four wide column">
			<%= link_to followers_path(user), class: "ui mini inverted pink statistic" do %>
				<div class="value"><%= user.followers.count %></div>
				<div class="label">粉丝</div>
			<% end %>
		</div>
		<div class="ui four wide column">
			<%= link_to followings_path(user), class: "ui mini inverted blue statistic" do %>
				<div class="value"><%= user.followings.count %></div>
				<div class="label">关注</div>
			<% end %>
		</div>
		<div class="ui eight wide column">
			<% if current_user.following?(user) %>
				<%= form_for(current_user.relationships.find_by(following_id: user.id), method: :delete, remote: true) do |f| %>
				<div><%= f.hidden_field :following_id %></div>
					<%= f.submit "Unfollow", class: "ui inverted teal button" %>
				<% end %>
			<% else %>
				<%= form_for(current_user.relationships.build(following_id: user.id), remote: true) do |f| %>
					<div><%= f.hidden_field :following_id %></div>
					<%= f.submit "Follow", class: "ui inverted blue button" %>
				<% end %>
			<% end unless current_user == user %>
		</div>
	</div>
</div>

app/views/relationships/create.js.erb
$('#follow').replaceWith("<%= j render partial: 'relationships/follow', locals: { user: @user } %>")

app/views/relationships/destroy.js.erb
$('#follow').replaceWith("<%= j render partial: 'relationships/follow', locals: { user: @user } %>")